routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'admin'], function () {

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('users', App\Http\Controllers\UserController::class);
Route::resource('settings', App\Http\Controllers\SettingsController::class);
Route::resource('categories', App\Http\Controllers\CategoriesController::class);
Route::resource('testimonials', App\Http\Controllers\TestimonialsController::class);
Route::delete('/categories/{id}', [App\Http\Controllers\CategoriesController::class, 'destroy'])->name('categories.destroy');
Route::delete('/testimonials/{id}', [App\Http\Controllers\CategoriesController::class, 'destroy'])->name('testimonials.destroy');
});

Route::group(['middleware' => ['web']], function () {
    Route::get('/', [App\Http\Controllers\FrontendController::class, 'index'])->name('public.index');
    Route::get('/about', [App\Http\Controllers\FrontendController::class, 'about'])->name('public.about');
    Route::get('/portfolio', [App\Http\Controllers\FrontendController::class, 'portfolio'])->name('public.portfolio');
    Route::get('/contact', [App\Http\Controllers\FrontendController::class, 'contact'])->name('public.contact');
    Route::get('/services', [App\Http\Controllers\FrontendController::class, 'services'])->name('public.services');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'role_id',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(Roles::class);

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Roles;
use App\Models\Settings;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{

    public function index()
    {
        $users = User::paginate(5);
        $roles = Roles::all();
        $data = ["users" => $users, "roles" => $roles];
        return view('users.index')->with($data);

    }

    public function create()
    {
        $roles = Roles::all();
        $data = ["roles" => $roles];
        return view('users.create')->with($data);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [

                'name' => ['required', 'string', 'max:255'],
                'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
                'password' => ['required', 'string', 'min:8', 'confirmed'],
                'role_id' => ['required']]
        );

        if ($validator->fails()) {
            return redirect('user/create')
                ->withErrors($validator)
                ->withInput();
        }

        User::create([

            'name' => $request->get('name'),
            'email'      => $request->get('email'),
            'role_id'    => $request->get('role_id'),
            'password'   => Hash::make($request->get('password'))

        ]);

        Session::flash('flash_message', 'User successfully created!');
        $users = User::all();
        $data = ["users" => $users];
        return view('users.index')->with($data);

    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $user = User::FindOrFail($id);
        $roles = Roles::all();
        $data = ["user" => $user, "roles" => $roles];
        return view('users.edit')->with($data);
    }


    public function update(Request $request, User $user)
    {
        if ($request->has('password') && !empty($request->get('password'))) {
            $input['password'] = Hash::make($request->get('password'));
        } else {
            $input = $request->except(['password']);
        }
        $user->fill($input)->save();
        $users = User::all();
        $data = ['users' => $users];
        return view('users.index')->with($data);
    }

    public function destroy($id)
    {
        $user = User::FindOrFail($id);
        $user->delete();
        $users = User::all();
        $data = ["users" => $users];
        return view('users.index')->with($data);
    }
}

resources/views/users/create.blade.php
@extends('layouts.dash')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                        <form method="POST" action="{{ route('users.store') }}">
                            @csrf
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Full Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>
                                <div class="col-md-6">
                                    <input id="name" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required>
                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>
                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="role_id" class="col-md-4 col-form-label text-md-right">Role</label>
                                <div class="col-md-6">
                                    <select class="form-control" name="role_id" required>
                                        @foreach($roles as $role)
                                            <option value="{{ $role->id }}">{{ $role->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Save User
                                    </button>
                                </div>
                            </div>
                        </form>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.dash')

@section('content')
    @if(Session::has('flash_message'))
        <div class="alert alert-success">
            {{ Session::get('flash_message') }}
        </div>
        @endif
        </form>
        <div class="col-12">
            <form action="{{ route('users.update', $user) }}" method="post">
                {{ method_field('PUT') }}
                @csrf
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control"
                               value="{{ $user->name }}" name="name" autocomplete="name" required
                               autofocus>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>
                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control"
                               name="email" value="{{ $user->email}}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Password</label>
                    <div class="col-md-6">
                        <input id="name" type="password" class="form-control" name="password">

                    </div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Confirm Password</label>
                    <div class="col-md-6">
                        <input id="name" type="password" class="form-control" name="password_confirmation">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="role" class="col-md-4 col-form-label text-md-right">Role</label>
                    <div class="col-md-6">
                        <select class="form-control" name="role_id" required>
                            @foreach($roles as $role)
                                <option value="{{ $role->id }}">{{ $role->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Save User
                        </button>
                    </div>
                </div>
            </form>
        </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.dash')

@section('content')




    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="text-center">All Users</h2>


                <div class="table-responsive g-mb-40">
                    <table class="table u-table--v3 g-color-black">
        <thead>
        <tr>
            <th>Full Name</th>
            <th>Role</th>
            <th>Email</th>
            <th>Created At</th>
            <th></th>
            <th></th>

        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->role->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->created_at }}</td>
                <td><a class="btn btn-warning" href="/users/{{ $user->id }}/edit"><i class="hs-admin-pencil-alt"></i></a></td>
                <td>
                    <form action="{{ route('users.destroy', $user) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger"><i class="hs-admin-eraser"></i></button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


@endsection