routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'admin'], function () {

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('users', App\Http\Controllers\UserController::class);
Route::resource('settings', App\Http\Controllers\SettingsController::class);
Route::resource('categories', App\Http\Controllers\CategoriesController::class);
Route::resource('testimonials', App\Http\Controllers\TestimonialsController::class);
Route::delete('/categories/{id}', [App\Http\Controllers\CategoriesController::class, 'destroy'])->name('categories.destroy');
Route::delete('/testimonials/{id}', [App\Http\Controllers\CategoriesController::class, 'destroy'])->name('testimonials.destroy');
});

Route::group(['middleware' => ['web']], function () {
    Route::get('/', [App\Http\Controllers\FrontendController::class, 'index'])->name('public.index');
    Route::get('/about', [App\Http\Controllers\FrontendController::class, 'about'])->name('public.about');
    Route::get('/portfolio', [App\Http\Controllers\FrontendController::class, 'portfolio'])->name('public.portfolio');
    Route::get('/contact', [App\Http\Controllers\FrontendController::class, 'contact'])->name('public.contact');
    Route::get('/services', [App\Http\Controllers\FrontendController::class, 'services'])->name('public.services');
});

app/Models/Testimonials.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Testimonials extends Model
{
    use HasFactory;

    protected $fillable = [

        'name',
        'company_name',
        'description'

    ];
}

app/Http/Controllers/TestimonialsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Testimonials;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class TestimonialsController extends Controller
{

    public function index()
    {
        $testimonials = Testimonials::all();
        $data = ['testimonials' => $testimonials];
        return view('testimonials.index')->with($data);

    }


    public function create()
    {
        return view('testimonials.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255'],
            'company_name' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string', 'max:255']
        ]);

        if ($validator->fails()) {

            return redirect('testimonials/create')
                ->withErrors($validator)
                ->withInput();
        }
        Testimonials::create([

            'name' => $request->get('name'),
            'company_name' => $request->get('company_name'),
            'description' => $request->get('description')

        ]);

        $testimonials = Testimonials::all();
        $data = ['testimonials' => $testimonials];
        return view('testimonials.index')->with($data);
    }


    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $testimonial = Testimonials::FindOrFail($id);
        $data = ['testimonial' => $testimonial];
        return view('testimonials.edit')->with($data);
    }

    public function update(Request $request, $id)
    {

        $testimonial = Testimonials::FindOrFail($id);
        $testimonial->update([
            'name'         => $request->get('name'),
            'company_name' => $request->get('company_name'),
            'desc'         => $request->get('desc'),
        ]);

        $testimonials = Testimonials::all();
        $data = ['testimonials' => $testimonials];
        return view('testimonials.index')->with($data);
    }

    public function destroy($id)
    {
        $testimonials = Testimonials::FindOrFail($id);
        $data = ['testimonials' => $testimonials];
        return view('testimonials.index')->with($data);
    }
}

resources/views/testimonials/create.blade.php
@extends('layouts.dash')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">New Testimonial</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('testimonials.store') }}">
                            @csrf


                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="company_name" class="col-md-4 col-form-label text-md-right">Company Name</label>

                                <div class="col-md-6">
                                    <input id="company_name" type="text" class="form-control @error('company_name') is-invalid @enderror" name="company_name" value="{{ old('company_name') }}" required autocomplete="company_name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                                <div class="col-md-6">
                                    <textarea id="description" type="text" class="form-control" @error('description') is-invalid @enderror" value="{{ old('description') }}" name="description" required></textarea>
                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Save Testimonial
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        CKEDITOR.replace( 'description' );
    </script>
@endsection

resources/views/testimonials/edit.blade.php
@extends('layouts.dash')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Testimonial</div>

                    <div class="card-body">
                        <form method="post" action="{{ route('testimonials.update', $testimonial) }}">
                            {{ method_field('PUT') }}
                            @csrf


                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $testimonial->name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="company_name" class="col-md-4 col-form-label text-md-right">Company Name</label>

                                <div class="col-md-6">
                                    <input id="company_name" type="text" class="form-control @error('company_name') is-invalid @enderror" name="company_name" value="{{ $testimonial->company_name }}" required autocomplete="company_name" autofocus>

                                    @error('company_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                                <div class="col-md-6">
                                    <textarea id="description" type="text" class="form-control" @error('description') is-invalid @enderror name="description" required>{{ $testimonial->description }}</textarea>
                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Save Changes
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        CKEDITOR.replace( 'description' );
    </script>
@endsection

resources/views/testimonials/index.blade.php
@extends('layouts.dash')
@section('content')
        <div class="col-12">
            <div class="table-responsive g-mb-40">
                <table class="table u-table--v3 g-color-black">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Company Name</th>
                        <th>Description</th>
                        <th></th>
                        <th></th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach($testimonials as $testimonial)
                        <tr>
                            <td>{{ $testimonial->name }}</td>
                            <td>{{ $testimonial->company_name }}</td>
                            <td>{{ $testimonial->description }}</td>
                            <td><a class="btn btn-warning" href="/testimonials/{{ $testimonial->id }}/edit"><i class="hs-admin-pencil-alt"></i></a>
                            </td>
                            <td>
                                <form action="{{ route('testimonials.destroy', $testimonial) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger"><i class="hs-admin-eraser"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>




@endsection