routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'admin'], function () {

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('users', App\Http\Controllers\UserController::class);
Route::resource('settings', App\Http\Controllers\SettingsController::class);
Route::resource('categories', App\Http\Controllers\CategoriesController::class);
Route::resource('testimonials', App\Http\Controllers\TestimonialsController::class);
Route::delete('/categories/{id}', [App\Http\Controllers\CategoriesController::class, 'destroy'])->name('categories.destroy');
Route::delete('/testimonials/{id}', [App\Http\Controllers\CategoriesController::class, 'destroy'])->name('testimonials.destroy');
});

Route::group(['middleware' => ['web']], function () {
    Route::get('/', [App\Http\Controllers\FrontendController::class, 'index'])->name('public.index');
    Route::get('/about', [App\Http\Controllers\FrontendController::class, 'about'])->name('public.about');
    Route::get('/portfolio', [App\Http\Controllers\FrontendController::class, 'portfolio'])->name('public.portfolio');
    Route::get('/contact', [App\Http\Controllers\FrontendController::class, 'contact'])->name('public.contact');
    Route::get('/services', [App\Http\Controllers\FrontendController::class, 'services'])->name('public.services');
});

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Helper\ImageStore;
use App\Models\Categories;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;

class CategoriesController extends Controller
{

    public function index()
    {
        $categories = Categories::getTree();
        $data = ['categories' => $categories];
        return view('categories.index')->with($data);
    }


    public function create()
    {
        $categories = Categories::all();
        $data = ['categories' => $categories];
        return view('categories.create')->with($data);
    }


    public function store(Request $request)
    {
        $name = $request->get('name');
        $parent_id = $request->get('parent_id');
        $image = $request->get('image');
        $slug = Str::slug($request->get('name'));


        $imageObj = new ImageStore($request, 'categories');
        $image = $imageObj->imageStore();


        if (!isset($parent_id)) {
            $data = [
                'name' => $name,
                'image' => $image,
                'slug' => $slug
            ];
            Categories::create($data);
            Session::flash('flash_message', 'Category successfully added!');
            return redirect()->back();
        }

        $category = Categories::FindOrFail($parent_id);

        Categories::create(['name' => $name, 'image' => $image], $category);
        Session::flash('flash_message', 'Category successfully added!');
        return redirect()->back();
    }
    public function show($id)
    {
        //
    }

    public function edit($id)
    {


        $category = Categories::FindOrFail($id);
        $categories = Categories::getList();
        $data = ['category' => $category, 'categories' => $categories];
        return view('categories.edit')->with($data);
    }

    public function update(Request $request, $id)
    {
        $category = Categories::FindOrFail($id);
        $input = $request->all();
        $category->fill($input)->save();
        Session::flash('flash_message', 'Category successfully edited.');

        $categories = Categories::getTree();
        $data = ['categories' => $categories];
        return view('categories.index')->with($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Categories::FindOrFail($id);
        $category->delete();
        $categories = Categories::all();
        $data = ['categories' => $categories];
        return redirect('admin/categories')->with($data);
    }
}

resources/views/categories/create.blade.php
@extends('layouts.dash')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">New Category</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('categories.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="logo_white" class="col-md-4 col-form-label text-md-right">Category Image</label>
                                <div class="col-md-6">
                                    <input id="logo_white" type="file"  name="logo_white">
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="parent_id" class="col-md-4 col-form-label text-md-right">Subcategory</label>
                                <div class="col-md-6">
                                    <select class="form-control @error('parent_id') is-invalid @enderror" name="parent_id"
                                    >
                                        <option value="">Main Category</option>
                                        {!! $categories !!}
                                    </select>
                                    @error('parent_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Save Category
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.dash')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Category</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('categories.update', $category) }}">
                            @csrf


                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $category->name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="parent_id" class="col-md-4 col-form-label text-md-right">Subcategory</label>
                                <div class="col-md-6">
                                    <select class="form-control @error('parent_id') is-invalid @enderror" name="parent_id"
                                    >
                                        <option value="">Main Category</option>
                                        {!! $categories !!}
                                    </select>
                                    @error('parent_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Save User
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.dash')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-8">
                {!! $categories  !!}
            </div>
        </div>

    </div>
@endsection