routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'admin'], function () {

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('users', App\Http\Controllers\UserController::class);
Route::resource('settings', App\Http\Controllers\SettingsController::class);
Route::resource('categories', App\Http\Controllers\CategoriesController::class);
Route::resource('testimonials', App\Http\Controllers\TestimonialsController::class);
Route::delete('/categories/{id}', [App\Http\Controllers\CategoriesController::class, 'destroy'])->name('categories.destroy');
Route::delete('/testimonials/{id}', [App\Http\Controllers\CategoriesController::class, 'destroy'])->name('testimonials.destroy');
});

Route::group(['middleware' => ['web']], function () {
    Route::get('/', [App\Http\Controllers\FrontendController::class, 'index'])->name('public.index');
    Route::get('/about', [App\Http\Controllers\FrontendController::class, 'about'])->name('public.about');
    Route::get('/portfolio', [App\Http\Controllers\FrontendController::class, 'portfolio'])->name('public.portfolio');
    Route::get('/contact', [App\Http\Controllers\FrontendController::class, 'contact'])->name('public.contact');
    Route::get('/services', [App\Http\Controllers\FrontendController::class, 'services'])->name('public.services');
});

app/Models/Settings.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Validator;

class Settings extends Model
{
    use HasFactory;

    protected $fillable = [

        'url',
        'logo_white',
        'logo_black',
        'title',
        'meta_title',
        'facebook',
        'instagram',
        'email',
        'phone',
        'address',
        'desc',
        'meta_desc',
        'keywords',
        'about_us',
        'meta_img'
    ];
}

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Settings;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use App\Http\Helper\ImageStore;

class SettingsController extends Controller
{

    public function index()
    {

        $settings = Settings::first();
        if ($settings) {
            return view('settings.index')->with(['settings' => $settings]);
        }
        return view('settings.create');
    }

    public function create()
    {
        return view('settings.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'url' => ['required', 'string', 'max:255'],
            'logo_white' => ['required', 'image'],
            'logo_black' => ['required', 'image'],
            'meta_img' => ['required', 'image'],
            'title' => ['required', 'string', 'max:255'],
            'meta_title' => ['required', 'string', 'max:255'],
            'facebook' => ['required', 'string', 'max:255'],
            'instagram' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'max:255'],
            'phone' => ['required', 'string', 'max:255'],
            'address' => ['required', 'string', 'max:255'],
            'desc' => ['required', 'string', 'max:255'],
            'meta_desc' => ['required', 'string', 'max:255'],
            'keywords' => ['required', 'string', 'max:255'],
            'about_us' => ['required', 'string', 'max:255']

        ]);
        if ($validator->fails()) {

            return redirect('/admin/settings/create')
                ->withErrors($validator)
                ->withInput();
        }


        $imageObj = new ImageStore($request, 'settings');
        $logo_white = $imageObj->imageStore('logo_white');

        $metaImgObj = new ImageStore($request, 'settings');
        $logo_black = $metaImgObj->imageStore('logo_black');


        $logoWhiteObj = new ImageStore($request, 'settings');
        $meta_img = $logoWhiteObj->imageStore('$meta_img');

            Settings::create([

                'url' => $request->get('url'),
                'logo_white' => $logo_white,
                'logo_black' => $logo_black,
                'meta_img' => $meta_img,
                'title' => $request->get('title'),
                'meta_title' => $request->get('meta_title'),
                'facebook' => $request->get('facebook'),
                'instagram' => $request->get('instagram'),
                'email' => $request->get('email'),
                'phone' => $request->get('phone'),
                'address' => $request->get('address'),
                'desc' => $request->get('desc'),
                'meta_desc' => $request->get('meta_desc'),
                'keywords' => $request->get('keywords'),
                'about_us' => $request->get('about_us')
            ]);

            Session::flash('flash_message', 'Settings successfully created!');
            return redirect()->back();
        }


    public function edit()
    {
        $settings = Settings::first();
        $data = ['settings' => $settings];
        return view('settings.edit')->with($data);
    }

    public function update(Request $request, $id)
    {
        $settings = Settings::FindOrFail($id);
        $input = $request->all();

        if ($request->hasFile('logo_white')) {
            $imageObj = new ImageStore($request, 'settings');
            $logo_white = $imageObj->imageStore();
            $input['logo_white'] = $logo_white;
        }
        if ($request->hasFile('meta_img')) {

            $metaImgObj = new ImageStore($request, 'settings');
            $meta_img = $metaImgObj->imageStore('meta_img');
            $input['meta_img'] = $meta_img;
        }
        if ($request->hasFile('logo_black')) {

            $logoWhiteObj = new ImageStore($request, 'settings');
            $logo_black = $logoWhiteObj->imageStore('logo_black');
            $input['logo_black'] = $logo_black;
        }

        $settings->fill($input)->save();

        return view('settings.index')->with(['settings' => $settings]);
    }



    public function destroy($id)
    {
        $settings = Settings::FindOrFail($id);
        $settings->delete();
        return view('settings.create');
    }
}

resources/views/settings/create.blade.php
@extends('layouts.dash')


@section('content')

    <div class="container">
        <div class="row">

            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif

            <div class="col-12">
                <form action="{{ route('settings.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group row">
                        <label for="logo_white" class="col-md-4 col-form-label text-md-right">Logo White</label>
                        <div class="col-md-6">
                            <input id="logo_white" type="file" class="btn btn-warning" name="logo_white">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="logo_black" class="col-md-4 col-form-label text-md-right">Logo Black</label>
                        <div class="col-md-6">
                            <input id="logo_black" type="file" class="btn btn-warning" name="logo_black">

                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="meta_img" class="col-md-4 col-form-label text-md-right">Meta Image</label>
                        <div class="col-md-6">
                            <input id="meta_img" type="file" class="btn btn-warning" name="meta_img">

                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="url" class="col-md-4 col-form-label text-md-right">Url</label>
                        <div class="col-md-6">
                            <input id="url" type="text" class="form-control @error('url') is-invalid @enderror" name="url" value="{{ old('url') }}"  required>
                            @error('url')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>
                        <div class="col-md-6">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}" name="title" required >
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="meta_title" class="col-md-4 col-form-label text-md-right">Meta Title</label>
                        <div class="col-md-6">
                            <input id="meta_title" type="text" class="form-control @error('meta_title') is-invalid @enderror" value="{{ old('meta_title') }}" name="meta_title" required >
                            @error('meta_title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="facebook" class="col-md-4 col-form-label text-md-right">Facebook</label>
                        <div class="col-md-6">
                            <input id="facebook" type="text" class="form-control @error('facebook') is-invalid @enderror" value="{{ old('facebook') }}" name="facebook" required>
                            @error('facebook')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="instagram" class="col-md-4 col-form-label text-md-right">Instagram</label>
                        <div class="col-md-6">
                            <input id="instagram" type="text" class="form-control @error('instagram') is-invalid @enderror" value="{{ old('instagram') }}" name="instagram" required>
                            @error('instagram')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>
                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}" name="email" required>
                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone" class="col-md-4 col-form-label text-md-right">Phone</label>
                        <div class="col-md-6">
                            <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" value="{{ old('phone') }}" name="phone" required>
                            @error('phone')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="address" class="col-md-4 col-form-label text-md-right">Address</label>
                        <div class="col-md-6">
                            <input id="address" type="text" class="form-control @error('address') is-invalid @enderror" value="{{ old('address') }}" name="address" required >
                            @error('address')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="desc" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6">
                            <textarea id="desc" type="text" class="form-control" name="desc" required></textarea>
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="meta_desc" class="col-md-4 col-form-label text-md-right">Meta Description</label>
                        <div class="col-md-6">
                            <textarea id="meta_desc" type="text" class="form-control" name="meta_desc" required></textarea>
                            @error('meta_desc')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="about_us" class="col-md-4 col-form-label text-md-right">About Us</label>
                        <div class="col-md-6">
                            <textarea id="about_us" type="text" class="form-control" name="about_us" required></textarea>
                            @error('about_us')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="keywords" class="col-md-4 col-form-label text-md-right">Keywords</label>
                        <div class="col-md-6">
                            <textarea id="keywords" type="text" class="form-control" name="keywords" required></textarea>
                            @error('keywords')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>



                    <div class="form-group row">

                        <div class="col-md-6">
                            <button type="submit" class="btn btn-info">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        CKEDITOR.replace( 'desc' );
        CKEDITOR.replace( 'about_us' );
        CKEDITOR.replace( 'meta_desc' );
    </script>
@endsection

@section('scripts')

    <script>
        $(document).ready(function () {
// Google Maps

            map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: 41.9991801, lng: 21.38801309999999},
                zoom: 15
            });

            var marker = new google.maps.Marker({
                position: {lat: 41.99599107489828, lng: 21.43222198486329},
                map: map,
                draggable: true
            });
            var input = document.getElementById('searchmap');
            var searchBox = new google.maps.places.SearchBox(input);
            map.controls[google.maps.ControlPosition.TOP_CENTER].push(input);
            google.maps.event.addListener(searchBox, 'places_changed', function () {
                var places = searchBox.getPlaces();
                var bounds = new google.maps.LatLngBounds();
                var i, place;
                for (i = 0; place = places[i]; i++) {
                    bounds.extend(place.geometry.location);
                    marker.setPosition(place.geometry.location);
                }
                map.fitBounds(bounds);
                map.setZoom(8);
            });
            google.maps.event.addListener(marker, 'position_changed', function () {
                var lat = marker.getPosition().lat();
                var lng = marker.getPosition().lng();
                $('#lat').val(lat);
                $('#lng').val(lng);
            });
            $("form").bind("keypress", function (e) {
                if (e.keyCode == 13) {
                    $("#searchmap").attr('value');
                    //add more buttons here
                    return false;
                }
            });
        });
    </script>

@endsection

resources/views/settings/edit.blade.php
@extends('layouts.dash')


@section('content')

    <div class="container">
        <div class="row">

            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif

            <div class="col-12">
                <form action="{{ route('settings.update', $settings ) }}" method="POST" enctype="multipart/form-data">
                    {{ method_field('PUT') }}
                    @csrf
                    <div class="form-group row">
                        <label for="logo_white" class="col-md-4 col-form-label text-md-right">Logo White</label>
                        <div class="col-md-6">
                            <input id="logo_white" type="file" class="btn btn-warning" name="logo_white">

                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="logo_black" class="col-md-4 col-form-label text-md-right">Logo Black</label>
                        <div class="col-md-6">
                            <input id="logo_black" type="file" class="btn btn-warning" name="logo_black">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="meta_img" class="col-md-4 col-form-label text-md-right">Meta Image</label>
                        <div class="col-md-6">
                            <input id="meta_img" type="file" class="btn btn-warning" name="meta_img">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="url" class="col-md-4 col-form-label text-md-right">Url</label>
                        <div class="col-md-6">
                            <input id="url" type="text" class="form-control @error('url') is-invalid @enderror" name="url" value="{{ $settings->url }}"  >
                            @error('url')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>
                        <div class="col-md-6">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" value="{{ $settings->title }}" name="title" required >
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="meta_title" class="col-md-4 col-form-label text-md-right">Meta Title</label>
                        <div class="col-md-6">
                            <input id="meta_title" type="text" class="form-control @error('meta_title') is-invalid @enderror" value="{{ $settings->meta_title }}" name="meta_title" required >
                            @error('meta_title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="facebook" class="col-md-4 col-form-label text-md-right">Facebook</label>
                        <div class="col-md-6">
                            <input id="facebook" type="text" class="form-control @error('facebook') is-invalid @enderror" value="{{ $settings->facebook }}" name="facebook" required>
                            @error('facebook')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="instagram" class="col-md-4 col-form-label text-md-right">Instagram</label>
                        <div class="col-md-6">
                            <input id="instagram" type="text" class="form-control @error('instagram') is-invalid @enderror" value="{{ $settings->instagram }}" name="instagram" required>
                            @error('instagram')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>
                        <div class="col-md-6">
                            <input id="email" type="text" class="form-control @error('email') is-invalid @enderror" value="{{ $settings->email }}" name="email" required>
                            @error('phone')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="phone" class="col-md-4 col-form-label text-md-right">Phone</label>
                        <div class="col-md-6">
                            <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" value="{{ $settings->phone }}" name="phone" required>
                            @error('phone')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="address" class="col-md-4 col-form-label text-md-right">Address</label>
                        <div class="col-md-6">
                            <input id="address" type="text" class="form-control @error('address') is-invalid @enderror" value="{{ $settings->address }}" name="address" required >
                            @error('address')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="desc" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6">
                            <textarea id="desc" type="text" class="form-control" name="desc" required>{{$settings->desc}}</textarea>
                            @error('desc')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="meta_desc" class="col-md-4 col-form-label text-md-right">Meta Description</label>
                        <div class="col-md-6">
                            <textarea id="meta_desc" type="text" class="form-control" name="meta_desc"
                                      required>{{$settings->meta_desc}}</textarea>
                            @error('meta_desc')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="about_us" class="col-md-4 col-form-label text-md-right">About Us</label>
                        <div class="col-md-6">
                            <textarea id="about_us" type="text" class="form-control" name="about_us" required>{{$settings->about_us}}</textarea>
                            @error('about_us')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="keywords" class="col-md-4 col-form-label text-md-right">Keywords</label>
                        <div class="col-md-6">
                            <textarea id="keywords" type="text" class="form-control" name="keywords" required>{{$settings->keywords}}</textarea>
                            @error('keywords')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-info">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        CKEDITOR.replace( 'desc' );
        CKEDITOR.replace( 'meta_desc' );
        CKEDITOR.replace( 'about_us' );
    </script>
@endsection

@section('scripts')

    <script>
        $(document).ready(function () {
// Google Maps

            map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: 41.9991801, lng: 21.38801309999999},
                zoom: 15
            });

            var marker = new google.maps.Marker({
                position: {lat: 41.99599107489828, lng: 21.43222198486329},
                map: map,
                draggable: true
            });
            var input = document.getElementById('searchmap');
            var searchBox = new google.maps.places.SearchBox(input);
            map.controls[google.maps.ControlPosition.TOP_CENTER].push(input);
            google.maps.event.addListener(searchBox, 'places_changed', function () {
                var places = searchBox.getPlaces();
                var bounds = new google.maps.LatLngBounds();
                var i, place;
                for (i = 0; place = places[i]; i++) {
                    bounds.extend(place.geometry.location);
                    marker.setPosition(place.geometry.location);
                }
                map.fitBounds(bounds);
                map.setZoom(8);
            });
            google.maps.event.addListener(marker, 'position_changed', function () {
                var lat = marker.getPosition().lat();
                var lng = marker.getPosition().lng();
                $('#lat').val(lat);
                $('#lng').val(lng);
            });
            $("form").bind("keypress", function (e) {
                if (e.keyCode == 13) {
                    $("#searchmap").attr('value');
                    //add more buttons here
                    return false;
                }
            });
        });
    </script>

@endsection